# Generated by Django 2.1.3 on 2018-12-21 19:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('location_name', models.CharField(max_length=20)),
                ('location_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_name', models.CharField(max_length=20)),
                ('product_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='ProductMovement',
            fields=[
                ('movement_id', models.IntegerField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('quantity', models.IntegerField()),
                ('from_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Location_at', to='logistic.Location')),
                ('p_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ProductMovement', to='logistic.Product')),
                ('to_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Location_to_be', to='logistic.Location')),
            ],
        ),
    ]
