# Generated by Django 2.1.3 on 2018-12-20 08:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='bank',
            fields=[
                ('name', models.CharField(max_length=50, unique=True)),
                ('bkid', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='branch',
            fields=[
                ('ifsc', models.CharField(max_length=11, primary_key=True, serialize=False)),
                ('branch_name', models.CharField(max_length=15)),
                ('address', models.TextField(max_length=1500)),
                ('city', models.CharField(max_length=12)),
                ('district', models.CharField(max_length=12)),
                ('state', models.CharField(max_length=12)),
                ('bankid', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='branch', to='searchapi.bank')),
            ],
        ),
    ]
