# Generated by Django 2.1.3 on 2018-12-20 08:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('searchapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='bankid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branch', to='searchapi.bank'),
        ),
    ]
