# Generated by Django 2.1.3 on 2018-12-20 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('searchapi', '0002_auto_20181220_0810'),
    ]

    operations = [
        migrations.RenameField(
            model_name='branch',
            old_name='bankid',
            new_name='bank',
        ),
    ]
